"""create_tables_for_postgresql

Revision ID: 0802ab08b1b7
Revises: 3be08a093053
Create Date: 2025-09-27 23:47:47.844344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0802ab08b1b7'
down_revision = '3be08a093053'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus'),
               existing_nullable=False)
    op.create_unique_constraint('uq_review_booking', 'reviews', ['booking_id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('user', 'admin', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'admin', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint('uq_review_booking', 'reviews', type_='unique')
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###